### ISSUE TITLE
Refactor Imperial.js to be more OO for better customization

### ISSUE THREAD

**Issue by GitGubM8** [Thrillberg/imperial#695]
Right now Imperial.js is a bit large, and maintenance isn't as convenient

Probably worth refactoring out the Entity, UseCases, and Coordination layer, which would help with bug-hunting as well as future expansion

**Comment by Thrillberg** [comment]
Yes! I think I've tried once or twice to refactor `imperial.js` but never had much success with it. If you can do it and tests still pass then great!

This reminded me of another debugging ticket to open: #696

**Comment by Thrillberg** [comment]
I'm going to close this ticket because we're kind of in a half-way state with refactoring which is fine (tests are passing and the game plays fine!). But we should probably keep tickets a bit more specific than this. I don't imagine work will resume on this unless someone wants to do it (I guess what I'm saying is that I don't want to do it).
