### ISSUE TITLE
Game previews

### ISSUE THREAD

**Issue by GitGubM8** [Thrillberg/imperial#755]
Having a preview like in OGS helps garner more attention as soon as user enters the front page
![image](https://user-images.githubusercontent.com/28380984/229607461-3498c925-268e-4664-b8fa-8bb860ccd209.png)

Perhaps we could do something similar
![image](https://user-images.githubusercontent.com/28380984/229607605-ddbd844a-ab23-4dae-81fe-ff117ff2189c.png)

**Comment by GitGubM8** [comment]
As mentioned in IRL chat, minor UX concerns about the visibility of units/territories in the scaled-down preview

Maybe another approach is to replace exact military unit counts with maneuver arrows similar to HOI
![image](https://user-images.githubusercontent.com/28380984/229608051-6581e535-6c4c-4bd8-8fae-3a20cb739d9c.png)

Here's my terrible paint job
![image](https://user-images.githubusercontent.com/28380984/229607876-ba675091-2a1f-4155-b96a-6aabd3c55fa6.png)

**Comment by Thrillberg** [comment]
Before tackling this one, we'll have to figure out how to transmit the game state from FE to BE to a cache and back to FE from the cache. Currently just naively using JSON isn't possible because the game state uses JS `Map`s and `Set`s, which would need to be converted into `Object`s and `Array`s before being JSON stringified.

This is a pretty big refactor so I'll split it out into its own issue: #763
